### ISSUE TITLE
Добавить проверку на длину слова в строке ответа

### ISSUE THREAD

**Issue by krisrazumeiko** [rawzes/pyQuiz#3]
При вводе ответа, который состоит из одной буквы, программа выдает сообщение о правильном ответе.

Шаги воспроизведения:
1. Запустить программу
2. Выбрать нужный режим
3. В строке ответа ввести одну букву, которая содержится в ответе
4. Нажать Enter

Ожидаемый результат: появляется сообщения об ошибке типа "Ответ не может содержать одну букву!"
Фактический результат: появляется сообщения о правильном ответе

**Comment by rawzes** [comment]
fixed in https://github.com/rawzes/pyQuiz/pull/12
