### ISSUE TITLE
Добавить валидацию ввода чисел

### ISSUE THREAD

**Issue by krisrazumeiko** [rawzes/pyQuiz#4]
При вводе чисел в строке ответа появляется сообщение о правильном ответе.

Шаги воспроизвеления:
1. Запустить программу
2. Выбрать нужный режим
3. Ввести число в строке для ответа
4. Нажать Enter

Ожидаемый результат: появление сообщения об ошибке типа "Ответ не может состоять из чисел!"
Фактический результат появление сообщения о правильном ответе

**Comment by rawzes** [comment]
@krisrazumeiko Not reproduced

**Comment by krisrazumeiko** [comment]
Not reproduced
