### ISSUE TITLE
Добавить валидацию ввода специальных символов

### ISSUE THREAD

**Issue by krisrazumeiko** [rawzes/pyQuiz#5]
При вводе специальных символов в строке ответа появляется сообщение о правильном ответе.

Шаги воспроизвеления:
1. Запустить программу
2. Выбрать нужный режим
3. Ввести число в строке для ответа
4. Нажать Enter

Ожидаемый результат: появление сообщения об ошибке типа "Ответ не может состоять из специальных символов!"
Фактический результат появление сообщения о правильном ответе

**Comment by rawzes** [comment]
@krisrazumeiko  Not reproduced

**Comment by krisrazumeiko** [comment]
Not reproduced
