### ISSUE TITLE
Добавить возможность повтора вопроса

### ISSUE THREAD

**Issue by krisrazumeiko** [rawzes/pyQuiz#6]
При вводе пустого ответа добавить возможность, чтобы этот же вопрос снова повторился

Шаги воспроизвеления:
1. Запустить программу
2. Выбрать нужный режим
3. Ничего не вводить в строке для ответа
4. Нажать Enter

Ожидаемый результат: появляется один и тот же вопрос после нажатия Enter
Фактический результат появляется следующий вопрос после нажатия Enter

**Comment by rawzes** [comment]
Fixed in https://github.com/rawzes/pyQuiz/pull/7
